#name, main, version and api are required
name: ExamplePlugin
main: ExamplePlugin\MainClass
version: 0.0.2
api: [1.0.0]

load: POSTWORLD
author: PocketMine Team
description: Example plugin showing the new API
website: https://github.com/PocketMine/ExamplePlugin
commands:
 hi:
  description: Hi command
  usage: "Usage: /hi"
  permission: exampleplugin.command.hi
 tst:
  description: Test command
  usage: "Usage: /tst"
  permission: exampleplugin.command.tst
 soo:
  description: Say hi to Sydney command
  usage: "Usage: /soo"  
permissions:
 exampleplugin.command.hi:
  description: "Allows the user to run the hi command"
  default: true
 exampleplugin.command.tst:
  description: "Allows the user to run the tst command"
  default: true